// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.project.domain;

import com.roo.project.domain.AppRole;

privileged aspect AppRole_Roo_JavaBean {
    
    public String AppRole.getName() {
        return this.name;
    }
    
    public void AppRole.setName(String name) {
        this.name = name;
    }
    
}
