// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.project.domain;

import com.roo.project.domain.AppUserRole;
import com.roo.project.domain.AppUserRoleDataOnDemand;
import com.roo.project.domain.AppUserRoleIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppUserRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppUserRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppUserRoleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppUserRoleIntegrationTest: @Transactional;
    
    @Autowired
    AppUserRoleDataOnDemand AppUserRoleIntegrationTest.dod;
    
    @Test
    public void AppUserRoleIntegrationTest.testCountAppUserRoles() {
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to initialize correctly", dod.getRandomAppUserRole());
        long count = AppUserRole.countAppUserRoles();
        Assert.assertTrue("Counter for 'AppUserRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppUserRoleIntegrationTest.testFindAppUserRole() {
        AppUserRole obj = dod.getRandomAppUserRole();
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to provide an identifier", id);
        obj = AppUserRole.findAppUserRole(id);
        Assert.assertNotNull("Find method for 'AppUserRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AppUserRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AppUserRoleIntegrationTest.testFindAllAppUserRoles() {
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to initialize correctly", dod.getRandomAppUserRole());
        long count = AppUserRole.countAppUserRoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'AppUserRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AppUserRole> result = AppUserRole.findAllAppUserRoles();
        Assert.assertNotNull("Find all method for 'AppUserRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AppUserRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppUserRoleIntegrationTest.testFindAppUserRoleEntries() {
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to initialize correctly", dod.getRandomAppUserRole());
        long count = AppUserRole.countAppUserRoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AppUserRole> result = AppUserRole.findAppUserRoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AppUserRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AppUserRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppUserRoleIntegrationTest.testFlush() {
        AppUserRole obj = dod.getRandomAppUserRole();
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to provide an identifier", id);
        obj = AppUserRole.findAppUserRole(id);
        Assert.assertNotNull("Find method for 'AppUserRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAppUserRole(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AppUserRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppUserRoleIntegrationTest.testMergeUpdate() {
        AppUserRole obj = dod.getRandomAppUserRole();
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to provide an identifier", id);
        obj = AppUserRole.findAppUserRole(id);
        boolean modified =  dod.modifyAppUserRole(obj);
        Integer currentVersion = obj.getVersion();
        AppUserRole merged = (AppUserRole)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AppUserRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppUserRoleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to initialize correctly", dod.getRandomAppUserRole());
        AppUserRole obj = dod.getNewTransientAppUserRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AppUserRole' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'AppUserRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AppUserRoleIntegrationTest.testRemove() {
        AppUserRole obj = dod.getRandomAppUserRole();
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppUserRole' failed to provide an identifier", id);
        obj = AppUserRole.findAppUserRole(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AppUserRole' with identifier '" + id + "'", AppUserRole.findAppUserRole(id));
    }
    
}
