// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.project.domain;

import com.roo.project.domain.AppUserDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AppUserDataOnDemand_Roo_Configurable {
    
    declare @type: AppUserDataOnDemand: @Configurable;
    
}
